apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  # Set the number of pods you want with `replicas`
  replicas: 3
  # Define the pod you want to manage in the `template` section. Copy the meat
  # of an existing pod-definition (don't include the apiVersion or kind fields)
  template:
    metadata:
      name: myapp-prod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx

