apiVersion: v1
kind: Service
metadata:
  name: myapp-service-backend-ip

spec:
  type: ClusterIP
  ports:
    - targetPort: 80 # Port on the pod
      port: 80       # Port on the service
  selector:
    app: myapp
    type: front-end
